@Home.Automation.Api_HostAddress = http://localhost:5238

GET {{Home.Automation.Api_HostAddress}}/dashboard/
Accept: application/json

###
POST {{Home.Automation.Api_HostAddress}}/devices/register
Content-type: application/json
Accept: application/json
{
  "Label": "Sample temp1 device",
  "SensorType": 0
}

###
POST {{Home.Automation.Api_HostAddress}}/devices/register
Content-type: application/json
Accept: application/json
{
  "Label": "Garage door 04", 
  "SensorType": 1,
  "DoorSensor": 
  {
    "DoorStatus": 0,
    "SendStatusChangeEmails": true, 
    "OpenReminderTimeSpan": null
  }
}

###
GET {{Home.Automation.Api_HostAddress}}/devices/temperature_sensors
Accept: application/json