@Home.Automation.Api_HostAddress = http://localhost:5238

GET {{Home.Automation.Api_HostAddress}}/dashboard/
Accept: application/json

###
POST {{Home.Automation.Api_HostAddress}}/devices/register
Content-type: application/json
Accept: application/json
{
  "Name": "Sample temp1 device",
  "DeviceType": 0
}

###
POST {{Home.Automation.Api_HostAddress}}/devices/register
Content-type: application/json
Accept: application/json
{
  "Name": "Garage door 01", 
  "DeviceType": 1,
  "SendStatusChangeEmails": true, 
  "OpenReminderTimeSpan": "00:10:00"
}

###
GET {{Home.Automation.Api_HostAddress}}/devices/temperature_sensors
Accept: application/json